apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm-merlinite
  namespace: demo
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    labels:  
      app: vllm-merlinite
    model:
      modelFormat:
        name: pytorch
      runtime: vllm
      storageUri: pvc://vllm-models-cache
      env:
        - name: MODEL_NAME
          value: instructlab/merlinite-7b-lab
