apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
  resourceVersion: '21822937'
  name: validate-app
  labels:
    operator.tekton.dev/provider-type: community
spec:
  description: This Task runs tests in python connecting to a remote Selenium
  params:
    - name: SELENIUM_SERVER
      type: string
    - name: app-server
      type: string
  steps:
    - computeResources: {}
      image: 'registry.access.redhat.com/ubi8/python-39:latest'
      name: validate-app
      script: |
        pip install selenium==4.9.1
        python -c '
        from selenium import webdriver
        from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
        from selenium.webdriver.support import expected_conditions as EC
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support.ui import WebDriverWait

        driver = webdriver.Remote(
            desired_capabilities=webdriver.DesiredCapabilities.FIREFOX,
            command_executor="http://selenium.demo.svc.cluster.local:4444/wd/hub"
        )
        driver.get("$(params.app-server)")
        try:
          element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "//strong[text()=\"Response:\"]"))
          )
        finally:
          driver.quit()
        '
      workingDir: $(workspaces.workspace.path)
  workspaces:
    - description: The workspace containing the cloned repository
      name: workspace